services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  auth-backend:
    build: ./auth-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: authpassword
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - postgres

  weather-backend:
    build: ./weather-backend
    environment:
      SERVER_PORT: 8080
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - auth-backend

  auth-frontend:
    build: ./auth-frontend
    ports:
      - "3001:80"
    restart: unless-stopped
    depends_on:
      - auth-backend

  weather-frontend:
    build: ./weather-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - weather-backend

volumes:
  postgres_data: